# Generated by Django 3.2.12 on 2022-04-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0002_auto_20220410_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
